version: '3'
services:
    redis:
        image: redis:6.2.2-buster
        ports:
            - "6379:6379"

    publisher:
        build: ./init/publisher
        volumes:
            - ./src/publisher:/root/workspace
        depends_on:
            - redis
