from pathlib import Path
import os


class NoRosBrokerGenerator:
    def __init__(self):
        self._cfg_dict = None

        self._gen_name_k = None
        self._gen_sensors_k = None
        self._gen_vector_sensors = []
        self._gen_actuators_k = None
        self._gen_vector_actuators = []
        self._gen_commands_k = None
        self._gen_vector_commands = []

    def _initialize(self, cfg_dict, cfg_parse):
        self._cfg_dict = cfg_dict

        (
            self._gen_name_k,
            self._gen_sensors_k,
            self._gen_vector_sensors,
            self._gen_actuators_k,
            self._gen_vector_actuators,
            self._gen_commands_k,
            self._gen_vector_commands,
        ) = cfg_parse[:]

        self._sep = "/"
        self._ext = ".py"

        self._tab = "    "
        self._2tab = self._tab * 2
        self._3tab = self._tab * 3
        self._nl = "\n"

    def _initialize_broker(self):
        self._prefix = "."
        self._destdir = "out" + self._sep + self._gen_name_k + self._sep + "noros"
        Path(self._prefix + self._sep + self._destdir).mkdir(
            parents=True, exist_ok=True
        )

        self._filename = (
            self._prefix + self._sep + self._destdir + self._sep + "broker" + self._ext
        )

        payload = [
            "# rcp: BROKER MODULE" + self._nl,
            "# rcp: auto-generated noros foreign broker file" + self._nl,
            "# rcp: do not edit this file" + self._nl,
            self._nl,
        ]

        f = open(self._filename, "w")
        f.writelines(payload)
        f.close()

    def generate(self, cfg_dict, cfg_parse):
        self._initialize(cfg_dict, cfg_parse)

        self._initialize_broker()
        self._gen_broker_imports()

        self._gen_broker_redis_wrapper_common()
        self._gen_broker_redis_wrapper_class()

        self._finalize()

    # ##################################################
    # GEN EXTRA

    def _gen_broker_imports(self):
        payload = [
            "import redis" + self._nl,
            self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _finalize(self):
        print("finalize > noros > " + self._filename)
        os.system("black -q " + self._filename)

    # ##################################################
    # GEN REDIS WRAPPER

    def _gen_broker_redis_wrapper_common(self):
        payload = [
            'SERVER_ADDR = "0.0.0.0"' + self._nl,
            "SERVER_PORT = 6379" + self._nl,
            "SERVER_DRDB = 0" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_broker_redis_wrapper_class(self):
        payload = [
            "class RedisWrapper:" + self._nl,
            self._tab
            + "def __init__(self, host=SERVER_ADDR, port=SERVER_PORT, db=SERVER_DRDB):"
            + self._nl,
            self._2tab
            + "self._redis = redis.Redis(host=host, port=port, db=db)"
            + self._nl,
            self._2tab + "self._redis_pubsub = self._redis.pubsub()" + self._nl,
            self._nl,
            self._tab + "def publish(self, topic, data):" + self._nl,
            self._2tab + "return self._redis_pubsub.publish(topic, data)" + self._nl,
            self._nl,
            self._tab + "def subscribe(self, topic):" + self._nl,
            self._2tab + "return self._redis_pubsub.subscribe(topic)" + self._nl,
            self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()
