version: "3"

services:
    redis_server:
        image: redis
        ports:
            - "6379:6379"

    ros2_translater:
        image: ros:dashing
        volumes:
            - ./ros2:/root/workspace
        depends_on:
            - redis_server
        entrypoint: /root/workspace/start.sh

    ros2_cli_talker:
        image: ros:dashing
        volumes:
            - ./ros2_cli_talker:/root/workspace
        depends_on:
            - redis_server
            - ros2_translater
        entrypoint: /root/workspace/start.sh
