from pathlib import Path


class Generator:
    def __init__(self):
        self._cfg_dict = None

        self._gen_name_k = None
        self._gen_sensors_k = None
        self._gen_vector_sensors = []
        self._gen_actuators_k = None
        self._gen_vector_actuators = []
        self._gen_commands_k = None
        self._gen_vector_commands = []

    def _initialize(self, cfg_dict, cfg_parse):
        self._cfg_dict = cfg_dict

        (
            self._gen_name_k,
            self._gen_sensors_k,
            self._gen_vector_sensors,
            self._gen_actuators_k,
            self._gen_vector_actuators,
            self._gen_commands_k,
            self._gen_vector_commands,
        ) = cfg_parse[:]

        self._sep = "/"
        self._ext = ".py"

        self._prefix = "."
        self._destdir = "out"
        Path(self._prefix + self._sep + self._destdir).mkdir(
            parents=True, exist_ok=True
        )

        self._filename = (
            self._prefix
            + self._sep
            + self._destdir
            + self._sep
            + self._gen_name_k
            + self._ext
        )

        self._tab = "    "
        self._2tab = self._tab * 2
        self._3tab = self._tab * 3
        self._nl = "\n"

        payload = [
            "# rcp: auto-generated ros foreign interface file" + self._nl,
            "# rcp: do not edit this file" + self._nl,
            self._nl,
        ]

        f = open(self._filename, "w")
        f.writelines(payload)
        f.close()

    def generate(self, cfg_dict, cfg_parse):
        self._initialize(cfg_dict, cfg_parse)

        self._gen_main_class()
        self._gen_main_class__init__()
        # maybe other calls

        self._gen_sensors_class()
        self._gen_sensors_class__init__()
        for sensor in self._gen_vector_sensors:
            self._gen_sensors_inner_class(sensor)
            self._gen_sensors_inner_class_def(sensor)
        # other calls

        self._gen_actuators_class()
        self._gen_actuators_class__init__()
        for actuator in self._gen_vector_actuators:
            self._gen_actuators_inner_class(actuator)
            self._gen_actuators_inner_class_def(actuator)
            self._gen_actuators_inner_class_commands(actuator)
            self._gen_actuators_inner_class_commands_def(actuator)
        # other calls

    # ##################################################
    # GEN MAIN CLASS

    def _gen_main_class(self):
        payload = [
            "class " + self._gen_name_k.capitalize() + ":" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_main_class__init__(self):
        payload = [
            self._tab + "def __init__(self):" + self._nl,
            self._2tab + "self.sensors = _Sensors()" + self._nl,
            self._2tab + "self.actuators = _Actuators()" + self._nl,
            self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    # ##################################################
    # GEN SENSORS CLASS

    def _gen_sensors_class(self):
        payload = [
            "class _" + self._gen_sensors_k.capitalize() + ":" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_sensors_class__init__(self):
        payload = [self._tab + "def __init__(self):" + self._nl]
        for sensor in self._gen_vector_sensors:
            payload.append(
                self._2tab
                + "self."
                + sensor
                + " = _"
                + sensor.capitalize()
                + "()"
                + self._nl
            )
        payload.append(self._nl)

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_sensors_inner_class(self, sensor):
        payload = [
            "class _" + sensor.capitalize() + ":" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_sensors_inner_class_def(self, sensor):
        payload = [self._tab + "def __init__(self):" + self._nl]
        # TODO: initialize w/ correct values, hint required #
        for k in self._cfg_dict[self._gen_name_k][self._gen_sensors_k][sensor].keys():
            payload.append(self._2tab + "self." + k + " = " + "None" + self._nl)
        payload.append(self._nl)

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    # ##################################################
    # ACTUATORS SENSORS CLASS

    def _gen_actuators_class(self):
        payload = [
            "class _" + self._gen_actuators_k.capitalize() + ":" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_actuators_class__init__(self):
        payload = [self._tab + "def __init__(self):" + self._nl]
        for actuator in self._gen_vector_actuators:
            payload.append(
                self._2tab
                + "self."
                + actuator
                + " = _"
                + actuator.capitalize()
                + "()"
                + self._nl
            )
        payload.append(self._nl)

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_actuators_inner_class(self, actuator):
        payload = [
            "class _" + actuator.capitalize() + ":" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_actuators_inner_class_def(self, actuator):
        payload = [self._tab + "def __init__(self):" + self._nl]
        # TODO: initialize w/ correct values, hint required #
        for k in self._cfg_dict[self._gen_name_k][self._gen_actuators_k][
            actuator
        ].keys():
            if k != "commands":
                payload.append(self._2tab + "self." + k + " = " + "None" + self._nl)
            else:
                payload.append(
                    self._2tab
                    + "self."
                    + k
                    + " = _"
                    + actuator.capitalize()
                    + "Commands()"
                    + self._nl
                )
        payload.append(self._nl)

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_actuators_inner_class_commands(self, actuator):
        payload = [
            "class _" + actuator.capitalize() + "Commands" + ":" + self._nl,
        ]

        f = open(self._filename, "a")
        f.writelines(payload)
        f.close()

    def _gen_actuators_inner_class_commands_def(self, actuator):
        for cmd in self._cfg_dict[self._gen_name_k][self._gen_actuators_k][actuator][
            "commands"
        ]:
            payload = [self._tab + "def " + cmd + "(self):" + self._nl]
            payload.append(self._2tab + "pass" + self._nl)
            payload.append(self._nl)

            f = open(self._filename, "a")
            f.writelines(payload)
            f.close()
